export interface GlossaryTerm {
  id: string;
  term: string;
  short: string;
  long: string;
  category: "rendite" | "finanzierung" | "mietrecht" | "kosten" | "analyse" | "allgemein";
}

export const CATEGORY_LABELS: Record<GlossaryTerm["category"], string> = {
  rendite: "Rendite & Cashflow",
  finanzierung: "Finanzierung",
  mietrecht: "Mietrecht",
  kosten: "Kosten",
  analyse: "Analyse",
  allgemein: "Allgemein",
};

export const CATEGORY_COLORS: Record<GlossaryTerm["category"], { bg: string; fg: string }> = {
  rendite: { bg: "#E6F4EA", fg: "#2D6A4F" },
  finanzierung: { bg: "#E0ECFB", fg: "#1E4F8B" },
  mietrecht: { bg: "#FBE9E7", fg: "#9C3527" },
  kosten: { bg: "#FFF4E0", fg: "#92580B" },
  analyse: { bg: "#EFE6FB", fg: "#5B3E9B" },
  allgemein: { bg: "#F2F0EC", fg: "#57534E" },
};

export const GLOSSARY: GlossaryTerm[] = [
  { id: "hwb", term: "HWB", category: "allgemein",
    short: "Heizwärmebedarf – gibt an wie viel Energie ein Gebäude pro Jahr zum Heizen benötigt.",
    long: "Der Heizwärmebedarf (HWB) ist ein Kennwert aus dem Energieausweis und gibt in kWh/m²/Jahr an, wie viel Energie ein Gebäude pro Jahr für die Raumheizung benötigt. Je niedriger der Wert, desto energieeffizienter ist das Gebäude. In Österreich ist der Energieausweis beim Kauf oder der Vermietung einer Immobilie Pflicht." },
  { id: "reserve", term: "Reserve (Kauf & Nebenkosten)", category: "kosten",
    short: "Puffer für unvorhergesehene Kosten beim Kauf – z.B. Renovierung, Einrichtung.",
    long: "Die Reserve ist ein selbst gewählter Puffer der zum Kaufpreis und den Nebenkosten addiert wird. Er deckt unvorhergesehene Ausgaben ab wie kleinere Renovierungen, Einrichtung oder laufende Kosten in den ersten Monaten. Empfohlen werden 2–5% des Kaufpreises." },
  { id: "ruecklagenfonds", term: "Rücklagenfonds", category: "kosten",
    short: "Gemeinschaftliches Sparguthaben der Eigentümergemeinschaft für Reparaturen am Gebäude.",
    long: "Der Rücklagenfonds ist ein gemeinsames Konto der Eigentümergemeinschaft (WEG) für größere Reparaturen und Sanierungen am Gebäude – z.B. Dachreparatur, Liftaustausch, Fassadensanierung. Als Käufer übernimmst du den Anteil des Vorbesitzers. Die Höhe der monatlichen Rücklagenzahlung findest du in der Betriebskostenabrechnung." },
  { id: "ust_provision", term: "USt auf Provision", category: "kosten",
    short: "20% Mehrwertsteuer die zusätzlich zur Maklerprovision anfällt.",
    long: "In Österreich und Deutschland unterliegt die Maklerprovision der Umsatzsteuer (20% in AT, 19% in DE). Bei einer Provision von 3% netto ergibt sich eine Bruttoprovision von 3,6% (AT). In der Kalkulation wird immer die Bruttoprovision als tatsächliche Kosten verwendet." },
  { id: "zinsbindung", term: "Zinsbindung", category: "finanzierung",
    short: "Zeitraum in dem der vereinbarte Zinssatz fix bleibt und nicht verändert werden kann.",
    long: "Die Zinsbindung legt fest für wie lange der Zinssatz deines Kredits unveränderlich ist. Bei einer 10-jährigen Zinsbindung bleibt dein Zinssatz 10 Jahre gleich, danach wird er neu verhandelt (Anschlussfinanzierung). Längere Zinsbindung bedeutet mehr Planungssicherheit aber oft einen höheren Zinssatz." },
  { id: "fixzins_periode", term: "Fixzins-Periode", category: "finanzierung",
    short: "Der Zeitraum in dem ein fixer (nicht variabler) Zinssatz gilt.",
    long: "Die Fixzins-Periode ist die Dauer der Zinsbindung bei einem Fixzinskredit. Nach Ablauf dieser Periode wird der Zinssatz neu verhandelt oder der Kredit in einen variablen Zinssatz umgewandelt. Typische Laufzeiten sind 5, 10, 15 oder 20 Jahre." },
  { id: "tilgungsarten", term: "Tilgungsarten", category: "finanzierung",
    short: "Verschiedene Methoden den Kredit zurückzuzahlen – am häufigsten Annuität.",
    long: "Die häufigste Tilgungsart ist die Annuität: gleiche monatliche Rate, die sich aus Zinsen und Tilgung zusammensetzt. Am Anfang ist der Zinsanteil hoch, am Ende überwiegt die Tilgung. Alternativ gibt es endfällige Kredite (nur Zinsen zahlen, Kredit am Ende auf einmal) oder variable Tilgung." },
  { id: "sondertilgung", term: "Sondertilgung", category: "finanzierung",
    short: "Außerplanmäßige Rückzahlung eines Teils des Kredits um Zinsen zu sparen.",
    long: "Eine Sondertilgung ist eine zusätzliche Zahlung außerhalb der regulären Monatsrate. Sie reduziert die Restschuld und damit die zukünftigen Zinsen. Viele Banken erlauben jährliche Sondertilgungen bis zu 10% der ursprünglichen Kreditsumme kostenfrei. Mehr als das kann Vorfälligkeitsentschädigungen auslösen." },
  { id: "mietrechtliche_einschaetzung", term: "Mietrechtliche Einschätzung", category: "mietrecht",
    short: "Einordnung ob und wie das MRG (Mietrechtsgesetz) auf die Immobilie zutrifft.",
    long: "Das österreichische Mietrechtsgesetz (MRG) schränkt die Miethöhe und Kündigungsmöglichkeiten ein. Altbauten (vor 1945) fallen oft unter Vollanwendung des MRG mit streng regulierten Richtwertmieten. Neubauten und Einfamilienhäuser sind oft frei von MRG-Beschränkungen. Die Einschätzung gibt an wie viel Risiko durch Mietregulierung besteht." },
  { id: "zielrendite", term: "Zielrendite", category: "rendite",
    short: "Die Mindest-Bruttorendite die du für eine Immobilie als akzeptabel definiert hast.",
    long: "Die Zielrendite ist dein persönlicher Mindestwert für die Bruttorendite einer Immobilie. Sie dient als Vergleichsgröße: Liegt die tatsächliche Rendite darunter, ist die Immobilie aus reiner Renditeperspektive uninteressant. Typische Zielrenditen für Wohnimmobilien in Österreich liegen zwischen 3% und 5%." },
  { id: "asset_entwicklung", term: "Asset-Entwicklung", category: "analyse",
    short: "Prognose wie sich der Wert deiner Immobilie und dein Eigenkapital über Zeit entwickeln.",
    long: "Die Asset-Entwicklung zeigt drei Kurven: den prognostizierten Objektwert (basierend auf angenommener Wertsteigerung), die sinkende Restschuld (durch monatliche Tilgung) und dein wachsendes Eigenkapital (Objektwert minus Restschuld). Je früher sich die Kurven kreuzen, desto schneller baust du Vermögen auf." },
  { id: "darlehenshoehe", term: "Darlehenshöhe", category: "analyse",
    short: "Der ausstehende Kreditbetrag der im Zeitverlauf durch Tilgung sinkt.",
    long: "Der Chart zeigt wie sich deine Restschuld über die Laufzeit des Kredits entwickelt. Zu Beginn sinkt die Restschuld langsam (weil ein großer Teil der Rate aus Zinsen besteht), gegen Ende schneller. Der Schnittpunkt mit der X-Achse ist der Zeitpunkt an dem der Kredit vollständig abbezahlt ist." },
  { id: "cash_entwicklung", term: "Cash-Entwicklung", category: "analyse",
    short: "Kumulierter Cashflow über die Haltedauer – zeigt wann sich die Investition rechnet.",
    long: "Der Cash-Entwicklungs-Chart zeigt den aufgesummierten monatlichen Cashflow über die Jahre. Ist er negativ bedeutet das du monatlich draufzahlst. Der Break-even-Punkt ist erreicht wenn die Kurve die Nulllinie kreuzt – ab dann hat die Immobilie mehr eingebracht als sie gekostet hat." },
  { id: "abschreibung", term: "Abschreibung / AfA", category: "analyse",
    short: "Steuerlicher Abzug für den Wertverlust des Gebäudes – reduziert deine Steuerlast.",
    long: "Die Absetzung für Abnutzung (AfA) erlaubt es Vermietern den Gebäudewert steuerlich über die Nutzungsdauer abzuschreiben. In Österreich beträgt der Satz 1,5% p.a. des Gebäudewerts (nicht des Grundstücks). Bei einem Gebäudewert von € 200.000 ergibt das € 3.000 AfA pro Jahr die vom steuerpflichtigen Einkommen abgezogen werden können." },
  { id: "mietsteigerung", term: "Mietsteigerung", category: "analyse",
    short: "Jährliche prozentuale Erhöhung der Miete – oft an die Inflation gekoppelt.",
    long: "Die angenommene jährliche Mietsteigerung beeinflusst die langfristige Cashflow-Prognose erheblich. In Österreich orientiert sich die Richtwertmiete an der Inflationsrate. Freie Mieten können vertraglich indexiert werden. Historisch lagen Mietsteigerungen in Österreich bei 2–3% p.a." },
  { id: "wertsteigerung", term: "Wertsteigerung", category: "analyse",
    short: "Jährliche prozentuale Zunahme des Immobilienwerts – für langfristige Prognosen.",
    long: "Die angenommene jährliche Wertsteigerung ist eine Prognose für die Entwicklung des Immobilienwerts. Historisch lagen Wertsteigerungen für Wohnimmobilien in Österreich bei 2–4% p.a., in Wien höher. Diese Annahme beeinflusst direkt die Asset-Entwicklung und die Gesamtrendite-Berechnung." },
  { id: "leerstand", term: "Leerstand", category: "analyse",
    short: "Zeitraum in dem die Immobilie nicht vermietet ist und keine Mieteinnahmen fließen.",
    long: "Der Leerstand ist die Zeit zwischen zwei Mietverhältnissen oder bei Schwierigkeiten einen Mieter zu finden. In der Kalkulation wird ein Leerstandspuffer von typischerweise 4% der Jahresmiete (ca. 2 Wochen/Jahr) angesetzt. In Großstädten ist der tatsächliche Leerstand oft geringer, in strukturschwachen Regionen höher." },
  { id: "instandhaltungsreserve", term: "Instandhaltungsreserve", category: "kosten",
    short: "Monatlicher Rücklagebetrag für Reparaturen und Instandhaltung der Immobilie.",
    long: "Die Instandhaltungsreserve ist ein Betrag den du monatlich zurücklegst um zukünftige Reparaturen zu finanzieren. Faustregel: 1% des Kaufpreises pro Jahr (bei älteren Gebäuden mehr). Diese Reserve schützt vor unerwarteten Ausgaben und sollte in der Cashflow-Berechnung berücksichtigt werden." },
  { id: "kostensteigerung", term: "Kostensteigerung", category: "analyse",
    short: "Jährliche Erhöhung der Betriebskosten und Instandhaltungskosten.",
    long: "Die Kostensteigerung berücksichtigt dass Betriebskosten, Versicherungen und Reparaturen jährlich teurer werden. Typischerweise wird hier die allgemeine Inflationsrate von 2% p.a. angesetzt. Eine höhere Kostensteigerung als Mietsteigerung reduziert den Cashflow über die Zeit." },
  { id: "dscr", term: "DSCR", category: "finanzierung",
    short: "Debt Service Coverage Ratio – zeigt ob die Mieteinnahmen die Kreditrate decken.",
    long: "Der DSCR (Debt Service Coverage Ratio) ist das Verhältnis von Mieteinnahmen zur monatlichen Kreditrate. Ein DSCR über 1 bedeutet die Miete deckt die Rate. Ein DSCR von 1,2 bedeutet die Miete ist 20% höher als die Rate. Banken fordern oft einen DSCR von mindestens 1,1–1,2 für die Kreditvergabe." },
  { id: "bruttorendite", term: "Bruttorendite", category: "rendite",
    short: "Jahresmiete geteilt durch Kaufpreis – der einfachste Renditewert.",
    long: "Die Bruttorendite berechnet sich als: (Jahresmiete / Kaufpreis) × 100. Sie ist ein erster Anhaltspunkt für die Attraktivität einer Immobilie, berücksichtigt aber weder Kosten noch Finanzierung. Für einen fairen Vergleich sollte immer auch die Nettorendite betrachtet werden." },
  { id: "nettorendite", term: "Nettorendite", category: "rendite",
    short: "Rendite nach Abzug aller Kosten – realistischer als die Bruttorendite.",
    long: "Die Nettorendite berücksichtigt alle laufenden Kosten: (Jahresmiete − Betriebskosten − Rücklage − Leerstand) / Gesamtinvestition × 100. Sie ist aussagekräftiger als die Bruttorendite und gibt an was die Immobilie nach Kosten tatsächlich abwirft." },
  { id: "cashflow", term: "Cashflow", category: "rendite",
    short: "Monatlicher Überschuss oder Fehlbetrag nach allen Einnahmen und Ausgaben.",
    long: "Der monatliche Cashflow ist: Miete − Kreditrate − Betriebskosten − Rücklage − Leerstandspuffer. Ein positiver Cashflow bedeutet die Immobilie verdient sich selbst. Ein negativer Cashflow bedeutet du musst monatlich draufzahlen (was kurzfristig bei Wertsteigerung trotzdem sinnvoll sein kann)." },
  { id: "annuitaet", term: "Annuität", category: "finanzierung",
    short: "Die gleichbleibende monatliche Rate aus Zinsen und Tilgung.",
    long: "Die Annuität ist die monatliche Kreditrate die sich aus einem Zins- und einem Tilgungsanteil zusammensetzt. Die Gesamtrate bleibt gleich, aber das Verhältnis verschiebt sich: Am Anfang überwiegt der Zinsanteil, mit der Zeit steigt der Tilgungsanteil. Für Käufer bedeutet das volle Planungssicherheit über die gesamte Zinsbindung." },
  { id: "annuitaetendarlehen", term: "Annuitätendarlehen", category: "finanzierung",
    short: "Die häufigste Kreditform – gleichbleibende Rate, steigender Tilgungsanteil.",
    long: "Beim Annuitätendarlehen bleibt die monatliche Rate konstant. Weil Zinsen nur auf die Restschuld berechnet werden, sinkt der Zinsanteil mit jeder Zahlung – und der Tilgungsanteil steigt automatisch. Das führt dazu, dass der Kredit am Ende der Laufzeit schneller abbezahlt wird als am Anfang." },
  { id: "auflassung", term: "Auflassung / Auflassungsvormerkung", category: "allgemein",
    short: "Die Einigung über den Eigentumsübergang, beim Notar erklärt und ins Grundbuch eingetragen.",
    long: "Die Auflassung ist die notarielle Einigungserklärung zwischen Käufer und Verkäufer über den Eigentumsübergang. Die Auflassungsvormerkung sichert den Käufer ab: Sie wird ins Grundbuch eingetragen und verhindert, dass der Verkäufer das Grundstück nochmals verkauft oder belastet. Bis zur endgültigen Eintragung als Eigentümer ist die Vormerkung der wichtigste Schutz des Käufers." },
  { id: "beleihungswert", term: "Beleihungswert", category: "finanzierung",
    short: "Der von der Bank ermittelte nachhaltige Wert einer Immobilie als Kreditsicherheit.",
    long: "Der Beleihungswert ist der Wert den eine Bank einer Immobilie als langfristige Sicherheit beimisst. Er liegt immer unter dem aktuellen Marktwert, weil die Bank mögliche Wertschwankungen einrechnet. Hypothekenbanken beleihen üblicherweise bis zu 60% des Beleihungswerts. Für Käufer ist er relevant weil er die maximale Kredithöhe beeinflusst." },
  { id: "beleihungsgrenze", term: "Beleihungsgrenze", category: "finanzierung",
    short: "Der maximale Kreditbetrag den eine Bank bezogen auf den Beleihungswert vergibt.",
    long: "Die Beleihungsgrenze ist der prozentuale Anteil des Beleihungswerts den eine Bank als Kredit auszahlt. Hypothekenbanken liegen typischerweise bei 60%, Geschäftsbanken gehen oft bis 80% des Marktwerts. Je niedriger die Beleihungsgrenze desto mehr Eigenkapital brauchst du." },
  { id: "bodenrichtwert", term: "Bodenrichtwert", category: "allgemein",
    short: "Richtwert für den Preis eines Grundstücks in Euro pro Quadratmeter.",
    long: "Der Bodenrichtwert gibt den durchschnittlichen Preis für Grund und Boden in einer bestimmten Lage an. Er wird vom Gutachterausschuss aus tatsächlichen Kaufpreisen abgeleitet und in Euro pro m² angegeben. Für Käufer ist er nützlich um einzuschätzen ob der Grundstücksanteil eines Kaufpreises realistisch ist." },
  { id: "denkmalschutz", term: "Denkmalschutz", category: "allgemein",
    short: "Staatlicher Schutz eines Gebäudes wegen kultureller oder historischer Bedeutung.",
    long: "Ein denkmalgeschütztes Gebäude darf nur eingeschränkt verändert werden. Für Investoren bedeutet das höhere Sanierungskosten und behördliche Auflagen, aber auch steuerliche Vorteile: In Österreich und Deutschland gibt es erhöhte AfA-Sätze und Sonderabschreibungen für denkmalgeschützte Immobilien. Der Energieausweis ist bei Denkmälern unter bestimmten Umständen nicht erforderlich." },
  { id: "dienstbarkeit", term: "Dienstbarkeit", category: "allgemein",
    short: "Ein eingetragenes Nutzungsrecht an einem fremden Grundstück.",
    long: "Eine Dienstbarkeit berechtigt jemanden ein Grundstück auf eine bestimmte Weise zu nutzen – etwa ein Wegerecht (Durchgang), ein Leitungsrecht (Kabel, Rohre) oder ein Wohnrecht. Dienstbarkeiten sind im Grundbuch Abt. II eingetragen und gehen beim Kauf auf den neuen Eigentümer über. Vor dem Kauf immer Grundbuch prüfen." },
  { id: "effektivzins", term: "Effektivzins", category: "finanzierung",
    short: "Der tatsächliche Jahreszins inklusive aller Gebühren – der einzig faire Vergleichswert.",
    long: "Der Effektivzins berücksichtigt nicht nur den Nominalzins sondern auch Bearbeitungsgebühren, Kontoführungsgebühren und den Zinseszinseffekt. Nur der Effektivzins ermöglicht einen fairen Vergleich zwischen verschiedenen Kreditangeboten. In Österreich und Deutschland müssen Banken den Effektivzins ausweisen." },
  { id: "energieausweis", term: "Energieausweis", category: "allgemein",
    short: "Pflichtdokument beim Verkauf und Vermieten – zeigt den Energiebedarf einer Immobilie.",
    long: "Der Energieausweis bewertet die energetische Qualität eines Gebäudes und muss bei Besichtigungen unaufgefordert vorgelegt werden. Es gibt zwei Varianten: den verbrauchsorientierten Ausweis (basiert auf tatsächlichem Verbrauch) und den bedarfsorientierten Ausweis (basiert auf bauphysikalischen Berechnungen). Wichtigste Kennzahlen: HWB (Heizwärmebedarf) und fGEE (Gesamtenergieeffizienzfaktor). Gültigkeit: 10 Jahre." },
  { id: "erbbaurecht", term: "Erbbaurecht", category: "allgemein",
    short: "Das Recht auf einem fremden Grundstück ein Gebäude zu errichten und zu nutzen.",
    long: "Beim Erbbaurecht kaufst du nicht das Grundstück sondern nur das Recht darauf zu bauen und zu wohnen. Dafür zahlst du dem Grundstückseigentümer einen jährlichen Erbbauzins. Erbbaurechte werden typischerweise für 60–99 Jahre vergeben. Der Vorteil: niedrigerer Kaufpreis. Der Nachteil: Nach Ablauf fällt das Gebäude an den Grundstückseigentümer. Für Investoren relevant wegen Finanzierbarkeit und Wiederverkauf." },
  { id: "flurstuck", term: "Flurstück", category: "allgemein",
    short: "Die amtlich vermessene und eindeutig bezeichnete kleinste Einheit im Kataster.",
    long: "Ein Flurstück ist ein genau abgegrenzter Teil der Erdoberfläche mit eigener Nummer im Liegenschaftskataster. Ein Grundstück kann aus mehreren Flurstücken bestehen. Die Flurstücksnummer findest du im Grundbuch-Bestandsverzeichnis. Beim Kauf wird im Kaufvertrag immer auf die exakten Flurstücksnummern Bezug genommen." },
  { id: "gemeinschaftseigentum", term: "Gemeinschaftseigentum", category: "allgemein",
    short: "Teile des Gebäudes die allen Eigentümern gemeinsam gehören.",
    long: "Zum Gemeinschaftseigentum einer Wohnungseigentumsanlage zählen alle Teile des Gebäudes die nicht im Sondereigentum eines einzelnen Eigentümers stehen: Fassade, Dach, Keller, Treppenhaus, Aufzug, Heizungsanlage. Die Kosten für das Gemeinschaftseigentum werden auf alle Eigentümer nach Miteigentumsanteilen aufgeteilt." },
  { id: "grundbuch", term: "Grundbuch", category: "allgemein",
    short: "Das amtliche Register aller Grundstücke mit Eigentümer, Rechten und Belastungen.",
    long: "Das Grundbuch ist das wichtigste Dokument beim Immobilienkauf. Es enthält in drei Abteilungen: Abt. I den Eigentümer, Abt. II Lasten und Beschränkungen (z.B. Wegerecht, Vorkaufsrecht), Abt. III Grundpfandrechte (z.B. Hypothek, Grundschuld). Als Käufer solltest du vor dem Kauf immer einen aktuellen Grundbuchauszug prüfen." },
  { id: "grundschuld", term: "Grundschuld", category: "finanzierung",
    short: "Das häufigste Sicherungsmittel der Bank bei Immobilienkrediten.",
    long: "Die Grundschuld ist eine Belastung im Grundbuch Abt. III die der Bank als Sicherheit für den Kredit dient. Anders als die Hypothek ist sie nicht direkt an die Kreditsumme gebunden und bleibt nach Kreditrückzahlung zunächst bestehen. Nach vollständiger Tilgung kann der Eigentümer die Löschung oder Abtretung der Grundschuld verlangen." },
  { id: "hausgeld", term: "Hausgeld", category: "kosten",
    short: "Monatliche Vorauszahlung an die Eigentümergemeinschaft für Betrieb und Rücklage.",
    long: "Das Hausgeld ist die monatliche Zahlung die ein Wohnungseigentümer an die Eigentümergemeinschaft leistet. Es deckt Betriebskosten (Heizung, Reinigung, Versicherung), Verwaltungskosten und den Anteil an der Instandhaltungsrücklage ab. Für Investoren wichtig: Das Hausgeld läuft auch bei Leerstand weiter. Nicht umlagefähiger Anteil schmälert den Cashflow." },
  { id: "hypothek", term: "Hypothek", category: "finanzierung",
    short: "Eine ältere Form der Kreditsicherung – heute meist durch die Grundschuld ersetzt.",
    long: "Die Hypothek ist ein Grundpfandrecht das direkt an die Kreditschuld gebunden ist. Mit jeder Tilgungsrate sinkt auch die Hypothek. In der Praxis hat die Grundschuld die Hypothek weitgehend abgelöst, weil sie flexibler ist. Der Begriff wird im Alltag aber oft synonym für jede Art von Immobilienkredit verwendet." },
  { id: "indexmiete", term: "Indexmiete", category: "mietrecht",
    short: "Miete die sich automatisch nach dem Verbraucherpreisindex entwickelt.",
    long: "Bei einer Indexmiete ist die Mietanpassung vertraglich an den VPI (Verbraucherpreisindex) gekoppelt. Steigt die Inflation, steigt auch die Miete – und umgekehrt. In Österreich gelten für indexierte Mietverträge besondere Regeln. Für Investoren bietet die Indexmiete Schutz vor Inflation, bindet aber auch an die Preisentwicklung." },
  { id: "liegenschaftszins", term: "Liegenschaftszins", category: "rendite",
    short: "Der marktübliche Zinssatz zur Bewertung von Grundstücken beim Ertragswertverfahren.",
    long: "Der Liegenschaftszins ist ein zentraler Faktor bei der Immobilienbewertung nach dem Ertragswertverfahren. Er drückt das Verhältnis zwischen Bodenwert und Reinertrag aus. Hohe Liegenschaftszinsen signalisieren höheres Risiko, niedrige Zinsen stehen für sichere Lagen. In Großstädten liegen die Liegenschaftszinsen für Wohnimmobilien oft zwischen 2–4%." },
  { id: "mietpreisbremse", term: "Mietpreisbremse", category: "mietrecht",
    short: "Deutsches Instrument das Neuvertragsmieten auf max. 10% über Vergleichsmiete begrenzt.",
    long: "Die Mietpreisbremse gilt in Deutschland in Regionen mit angespanntem Wohnungsmarkt. Bei Neuvermietung darf die Miete höchstens 10% über der ortsüblichen Vergleichsmiete liegen. Ausnahmen: Neubauten nach 2014, umfassend modernisierte Wohnungen. In Österreich gibt es stattdessen das Richtwertmietsystem und das Mietenpaket 2026." },
  { id: "mietspiegel", term: "Mietspiegel", category: "mietrecht",
    short: "Übersicht über die ortsübliche Vergleichsmiete in einer Stadt oder Gemeinde.",
    long: "Der Mietspiegel gibt Auskunft über die durchschnittlichen Mieten in einer Gemeinde nach Lage, Größe, Ausstattung und Zustand. Er dient als Grundlage für Mieterhöhungen und ist für Vermieter wie Mieter ein wichtiges Instrument. In Österreich gibt es keinen einheitlichen Mietspiegel – hier gelten Richtwerte und Kategoriemieten." },
  { id: "miteigentumsanteil", term: "Miteigentumsanteil (MEA)", category: "allgemein",
    short: "Der rechnerische Bruchteil am Gemeinschaftseigentum einer Wohnanlage.",
    long: "Der Miteigentumsanteil gibt an welcher Anteil am gesamten Grundstück und Gemeinschaftseigentum einer Wohnungseigentumsanlage dir gehört. Er bestimmt mit welchem Prozentsatz du dich an Kosten für Reparaturen, Sanierungen und Verwaltung beteiligst. In Österreich wird er in der Nutzwertfestsetzung (Parifizierung) festgelegt." },
  { id: "notar", term: "Notar", category: "allgemein",
    short: "Notarielle Beurkundung ist beim Immobilienkauf in AT und DE Pflicht.",
    long: "Der Notar beurkundet den Kaufvertrag, prüft die Identität beider Parteien und sorgt für die korrekte Grundbucheintragung. In Österreich übernimmt der Notar oft auch die Treuhandabwicklung: Der Kaufpreis wird zunächst auf das Treuhandkonto des Notars überwiesen und erst nach Eintragung der Auflassungsvormerkung an den Verkäufer weitergeleitet. Die Notarkosten trägt in der Regel der Käufer." },
  { id: "sachwertverfahren", term: "Sachwertverfahren", category: "allgemein",
    short: "Bewertungsmethode die den Substanzwert eines Gebäudes ermittelt.",
    long: "Das Sachwertverfahren ermittelt den Wert einer Immobilie über die Baukosten abzüglich Abnutzung plus Bodenwert. Es wird vor allem bei selbstgenutzten Ein- und Zweifamilienhäusern angewandt, wo keine Mieteinnahmen als Bewertungsgrundlage dienen. Für Renditeobjekte ist das Ertragswertverfahren relevanter." },
  { id: "sondereigentum", term: "Sondereigentum", category: "allgemein",
    short: "Der Teil einer Eigentumswohnung der ausschließlich dem einzelnen Eigentümer gehört.",
    long: "Das Sondereigentum umfasst die Räume der Wohnung selbst. Es steht dem Gemeinschaftseigentum gegenüber. Wichtig: Nicht alles was sich in der Wohnung befindet ist Sondereigentum. Tragende Wände, Fensterfronten (Außenseite) und Leitungen in den Wänden gehören zum Gemeinschaftseigentum. Was genau zum Sondereigentum gehört, steht in der Teilungserklärung." },
  { id: "spekulationssteuer", term: "Spekulationssteuer / ImmoESt", category: "analyse",
    short: "Steuer auf Gewinne beim Immobilienverkauf – in AT 30%, in DE nach 10 Jahren steuerfrei.",
    long: "In Österreich unterliegt jeder Gewinn aus dem Immobilienverkauf der Immobilienertragsteuer (ImmoESt) von 30% – unabhängig von der Haltedauer. Ausnahme: Hauptwohnsitzbefreiung bei mindestens 2 Jahren durchgehender Eigennutzung. In Deutschland gilt die Spekulationsfrist von 10 Jahren: Wird nach 10 Jahren verkauft ist der Gewinn steuerfrei. Eigennutzung im Verkaufsjahr und den zwei Vorjahren ist ebenfalls steuerfrei." },
  { id: "teilungserklarung", term: "Teilungserklärung", category: "allgemein",
    short: "Das Gründungsdokument einer Eigentümergemeinschaft – regelt Eigentumsverhältnisse und Rechte.",
    long: "Die Teilungserklärung legt fest wie ein Gebäude in Sondereigentum und Gemeinschaftseigentum aufgeteilt ist, welche Miteigentumsanteile jede Einheit hat und welche Regeln für die Gemeinschaft gelten. Sie ist im Grundbuch eingetragen und wird beim Kauf zur Pflichtlektüre. Besonders wichtig: Sondernutzungsrechte (z.B. Stellplatz, Garten) und Kostenverteilungsschlüssel." },
  { id: "vergleichswertverfahren", term: "Vergleichswertverfahren", category: "allgemein",
    short: "Bewertungsmethode die den Wert anhand vergleichbarer Verkäufe ermittelt.",
    long: "Das Vergleichswertverfahren ermittelt den Marktwert einer Immobilie aus tatsächlich erzielten Kaufpreisen ähnlicher Objekte. Es ist die gängigste Methode bei Eigentumswohnungen und Einfamilienhäusern. Die Qualität der Bewertung hängt davon ab wie viele und wie vergleichbare Referenzkäufe vorhanden sind." },
  { id: "vorfaelligkeitsentschaedigung", term: "Vorfälligkeitsentschädigung", category: "finanzierung",
    short: "Gebühr der Bank wenn du einen Fixzinskredit vorzeitig zurückzahlst.",
    long: "Wer einen Fixzinskredit vor Ablauf der Zinsbindung zurückzahlt muss der Bank den entgangenen Zinsgewinn ersetzen. In Österreich ist die Vorfälligkeitsentschädigung bei Fixzinskrediten auf max. 1% der vorzeitig zurückgezahlten Summe begrenzt (0,5% bei Restlaufzeit unter 1 Jahr). Ab 2027 steigt die Grenze auf max. 3%. Variabel verzinste Kredite können in Österreich jederzeit ohne Entschädigung zurückgezahlt werden." },
  { id: "vorkaufsrecht", term: "Vorkaufsrecht", category: "allgemein",
    short: "Das Recht eines Dritten eine Immobilie vor anderen Käufern zu erwerben.",
    long: "Ein Vorkaufsrecht berechtigt seinen Inhaber beim Verkauf einer Immobilie zu denselben Konditionen vorzukaufen die mit einem Dritten ausgehandelt wurden. Es kann im Grundbuch eingetragen sein (dingliches Vorkaufsrecht) oder nur schuldrechtlich vereinbart. Beim Kauf immer Grundbuch Abt. II prüfen ob ein Vorkaufsrecht eingetragen ist." },
  { id: "wohnflache", term: "Wohnflächenberechnung", category: "allgemein",
    short: "Wie die anrechenbare Fläche einer Wohnung berechnet wird.",
    long: "Die Wohnfläche ist nicht gleich der Grundfläche. Balkone, Terrassen und Loggien werden in Österreich und Deutschland nur anteilig angerechnet (meist 25–50%). Räume unter 2m Deckenhöhe zählen nur halb, unter 1m gar nicht. Keller, Garagen und Abstellräume außerhalb der Wohnung zählen grundsätzlich nicht zur Wohnfläche. Eine falsch angegebene Wohnfläche kann zur Mietminderung berechtigen." },
  { id: "zwangsversteigerung", term: "Zwangsversteigerung", category: "allgemein",
    short: "Staatlich angeordneter Verkauf einer Immobilie zur Befriedigung von Gläubigern.",
    long: "Bei einer Zwangsversteigerung verwertet das Gericht die Immobilie um Schulden des Eigentümers zu begleichen. Käufer können günstig erwerben, tragen aber erhöhte Risiken: kein Rücktrittsrecht, kaum Möglichkeit zur Besichtigung, mögliche Mieter oder andere Belastungen. Das Meistgebot muss sofort oder innerhalb kurzer Frist bezahlt werden. Für erfahrene Investoren kann das interessant sein." },
  { id: "zwischenfinanzierung", term: "Zwischenfinanzierung", category: "finanzierung",
    short: "Kurzfristiger Kredit der überbrückt wenn Eigenkapital noch nicht verfügbar ist.",
    long: "Eine Zwischenfinanzierung wird genutzt wenn der Kaufpreis fällig ist, das eigene Kapital aber noch gebunden ist (z.B. noch nicht verkaufte Immobilie, auslaufende Festgeldanlage). Die Zwischenfinanzierung wird durch das erwartete Kapital abgelöst. Sie läuft typischerweise maximal 2 Jahre und ist meist teurer als langfristige Kredite." },
];
