export interface GlossaryTerm {
  id: string;
  term: string;
  short: string;
  long: string;
  category: "rendite" | "finanzierung" | "mietrecht" | "kosten" | "analyse" | "allgemein";
}

export const CATEGORY_LABELS: Record<GlossaryTerm["category"], string> = {
  rendite: "Rendite & Cashflow",
  finanzierung: "Finanzierung",
  mietrecht: "Mietrecht",
  kosten: "Kosten",
  analyse: "Analyse",
  allgemein: "Allgemein",
};

export const CATEGORY_COLORS: Record<GlossaryTerm["category"], { bg: string; fg: string }> = {
  rendite: { bg: "#E6F4EA", fg: "#2D6A4F" },
  finanzierung: { bg: "#E0ECFB", fg: "#1E4F8B" },
  mietrecht: { bg: "#FBE9E7", fg: "#9C3527" },
  kosten: { bg: "#FFF4E0", fg: "#92580B" },
  analyse: { bg: "#EFE6FB", fg: "#5B3E9B" },
  allgemein: { bg: "#F2F0EC", fg: "#57534E" },
};

export const GLOSSARY: GlossaryTerm[] = [
  { id: "hwb", term: "HWB", category: "allgemein",
    short: "Heizwärmebedarf – gibt an wie viel Energie ein Gebäude pro Jahr zum Heizen benötigt.",
    long: "Der Heizwärmebedarf (HWB) ist ein Kennwert aus dem Energieausweis und gibt in kWh/m²/Jahr an, wie viel Energie ein Gebäude pro Jahr für die Raumheizung benötigt. Je niedriger der Wert, desto energieeffizienter ist das Gebäude. In Österreich ist der Energieausweis beim Kauf oder der Vermietung einer Immobilie Pflicht." },
  { id: "reserve", term: "Reserve (Kauf & Nebenkosten)", category: "kosten",
    short: "Puffer für unvorhergesehene Kosten beim Kauf – z.B. Renovierung, Einrichtung.",
    long: "Die Reserve ist ein selbst gewählter Puffer der zum Kaufpreis und den Nebenkosten addiert wird. Er deckt unvorhergesehene Ausgaben ab wie kleinere Renovierungen, Einrichtung oder laufende Kosten in den ersten Monaten. Empfohlen werden 2–5% des Kaufpreises." },
  { id: "ruecklagenfonds", term: "Rücklagenfonds", category: "kosten",
    short: "Gemeinschaftliches Sparguthaben der Eigentümergemeinschaft für Reparaturen am Gebäude.",
    long: "Der Rücklagenfonds ist ein gemeinsames Konto der Eigentümergemeinschaft (WEG) für größere Reparaturen und Sanierungen am Gebäude – z.B. Dachreparatur, Liftaustausch, Fassadensanierung. Als Käufer übernimmst du den Anteil des Vorbesitzers. Die Höhe der monatlichen Rücklagenzahlung findest du in der Betriebskostenabrechnung." },
  { id: "ust_provision", term: "USt auf Provision", category: "kosten",
    short: "20% Mehrwertsteuer die zusätzlich zur Maklerprovision anfällt.",
    long: "In Österreich und Deutschland unterliegt die Maklerprovision der Umsatzsteuer (20% in AT, 19% in DE). Bei einer Provision von 3% netto ergibt sich eine Bruttoprovision von 3,6% (AT). In der Kalkulation wird immer die Bruttoprovision als tatsächliche Kosten verwendet." },
  { id: "zinsbindung", term: "Zinsbindung", category: "finanzierung",
    short: "Zeitraum in dem der vereinbarte Zinssatz fix bleibt und nicht verändert werden kann.",
    long: "Die Zinsbindung legt fest für wie lange der Zinssatz deines Kredits unveränderlich ist. Bei einer 10-jährigen Zinsbindung bleibt dein Zinssatz 10 Jahre gleich, danach wird er neu verhandelt (Anschlussfinanzierung). Längere Zinsbindung bedeutet mehr Planungssicherheit aber oft einen höheren Zinssatz." },
  { id: "fixzins_periode", term: "Fixzins-Periode", category: "finanzierung",
    short: "Der Zeitraum in dem ein fixer (nicht variabler) Zinssatz gilt.",
    long: "Die Fixzins-Periode ist die Dauer der Zinsbindung bei einem Fixzinskredit. Nach Ablauf dieser Periode wird der Zinssatz neu verhandelt oder der Kredit in einen variablen Zinssatz umgewandelt. Typische Laufzeiten sind 5, 10, 15 oder 20 Jahre." },
  { id: "tilgungsarten", term: "Tilgungsarten", category: "finanzierung",
    short: "Verschiedene Methoden den Kredit zurückzuzahlen – am häufigsten Annuität.",
    long: "Die häufigste Tilgungsart ist die Annuität: gleiche monatliche Rate, die sich aus Zinsen und Tilgung zusammensetzt. Am Anfang ist der Zinsanteil hoch, am Ende überwiegt die Tilgung. Alternativ gibt es endfällige Kredite (nur Zinsen zahlen, Kredit am Ende auf einmal) oder variable Tilgung." },
  { id: "sondertilgung", term: "Sondertilgung", category: "finanzierung",
    short: "Außerplanmäßige Rückzahlung eines Teils des Kredits um Zinsen zu sparen.",
    long: "Eine Sondertilgung ist eine zusätzliche Zahlung außerhalb der regulären Monatsrate. Sie reduziert die Restschuld und damit die zukünftigen Zinsen. Viele Banken erlauben jährliche Sondertilgungen bis zu 10% der ursprünglichen Kreditsumme kostenfrei. Mehr als das kann Vorfälligkeitsentschädigungen auslösen." },
  { id: "mietrechtliche_einschaetzung", term: "Mietrechtliche Einschätzung", category: "mietrecht",
    short: "Einordnung ob und wie das MRG (Mietrechtsgesetz) auf die Immobilie zutrifft.",
    long: "Das österreichische Mietrechtsgesetz (MRG) schränkt die Miethöhe und Kündigungsmöglichkeiten ein. Altbauten (vor 1945) fallen oft unter Vollanwendung des MRG mit streng regulierten Richtwertmieten. Neubauten und Einfamilienhäuser sind oft frei von MRG-Beschränkungen. Die Einschätzung gibt an wie viel Risiko durch Mietregulierung besteht." },
  { id: "zielrendite", term: "Zielrendite", category: "rendite",
    short: "Die Mindest-Bruttorendite die du für eine Immobilie als akzeptabel definiert hast.",
    long: "Die Zielrendite ist dein persönlicher Mindestwert für die Bruttorendite einer Immobilie. Sie dient als Vergleichsgröße: Liegt die tatsächliche Rendite darunter, ist die Immobilie aus reiner Renditeperspektive uninteressant. Typische Zielrenditen für Wohnimmobilien in Österreich liegen zwischen 3% und 5%." },
  { id: "asset_entwicklung", term: "Asset-Entwicklung", category: "analyse",
    short: "Prognose wie sich der Wert deiner Immobilie und dein Eigenkapital über Zeit entwickeln.",
    long: "Die Asset-Entwicklung zeigt drei Kurven: den prognostizierten Objektwert (basierend auf angenommener Wertsteigerung), die sinkende Restschuld (durch monatliche Tilgung) und dein wachsendes Eigenkapital (Objektwert minus Restschuld). Je früher sich die Kurven kreuzen, desto schneller baust du Vermögen auf." },
  { id: "darlehenshoehe", term: "Darlehenshöhe", category: "analyse",
    short: "Der ausstehende Kreditbetrag der im Zeitverlauf durch Tilgung sinkt.",
    long: "Der Chart zeigt wie sich deine Restschuld über die Laufzeit des Kredits entwickelt. Zu Beginn sinkt die Restschuld langsam (weil ein großer Teil der Rate aus Zinsen besteht), gegen Ende schneller. Der Schnittpunkt mit der X-Achse ist der Zeitpunkt an dem der Kredit vollständig abbezahlt ist." },
  { id: "cash_entwicklung", term: "Cash-Entwicklung", category: "analyse",
    short: "Kumulierter Cashflow über die Haltedauer – zeigt wann sich die Investition rechnet.",
    long: "Der Cash-Entwicklungs-Chart zeigt den aufgesummierten monatlichen Cashflow über die Jahre. Ist er negativ bedeutet das du monatlich draufzahlst. Der Break-even-Punkt ist erreicht wenn die Kurve die Nulllinie kreuzt – ab dann hat die Immobilie mehr eingebracht als sie gekostet hat." },
  { id: "abschreibung", term: "Abschreibung / AfA", category: "analyse",
    short: "Steuerlicher Abzug für den Wertverlust des Gebäudes – reduziert deine Steuerlast.",
    long: "Die Absetzung für Abnutzung (AfA) erlaubt es Vermietern den Gebäudewert steuerlich über die Nutzungsdauer abzuschreiben. In Österreich beträgt der Satz 1,5% p.a. des Gebäudewerts (nicht des Grundstücks). Bei einem Gebäudewert von € 200.000 ergibt das € 3.000 AfA pro Jahr die vom steuerpflichtigen Einkommen abgezogen werden können." },
  { id: "mietsteigerung", term: "Mietsteigerung", category: "analyse",
    short: "Jährliche prozentuale Erhöhung der Miete – oft an die Inflation gekoppelt.",
    long: "Die angenommene jährliche Mietsteigerung beeinflusst die langfristige Cashflow-Prognose erheblich. In Österreich orientiert sich die Richtwertmiete an der Inflationsrate. Freie Mieten können vertraglich indexiert werden. Historisch lagen Mietsteigerungen in Österreich bei 2–3% p.a." },
  { id: "wertsteigerung", term: "Wertsteigerung", category: "analyse",
    short: "Jährliche prozentuale Zunahme des Immobilienwerts – für langfristige Prognosen.",
    long: "Die angenommene jährliche Wertsteigerung ist eine Prognose für die Entwicklung des Immobilienwerts. Historisch lagen Wertsteigerungen für Wohnimmobilien in Österreich bei 2–4% p.a., in Wien höher. Diese Annahme beeinflusst direkt die Asset-Entwicklung und die Gesamtrendite-Berechnung." },
  { id: "leerstand", term: "Leerstand", category: "analyse",
    short: "Zeitraum in dem die Immobilie nicht vermietet ist und keine Mieteinnahmen fließen.",
    long: "Der Leerstand ist die Zeit zwischen zwei Mietverhältnissen oder bei Schwierigkeiten einen Mieter zu finden. In der Kalkulation wird ein Leerstandspuffer von typischerweise 4% der Jahresmiete (ca. 2 Wochen/Jahr) angesetzt. In Großstädten ist der tatsächliche Leerstand oft geringer, in strukturschwachen Regionen höher." },
  { id: "instandhaltungsreserve", term: "Instandhaltungsreserve", category: "kosten",
    short: "Monatlicher Rücklagebetrag für Reparaturen und Instandhaltung der Immobilie.",
    long: "Die Instandhaltungsreserve ist ein Betrag den du monatlich zurücklegst um zukünftige Reparaturen zu finanzieren. Faustregel: 1% des Kaufpreises pro Jahr (bei älteren Gebäuden mehr). Diese Reserve schützt vor unerwarteten Ausgaben und sollte in der Cashflow-Berechnung berücksichtigt werden." },
  { id: "kostensteigerung", term: "Kostensteigerung", category: "analyse",
    short: "Jährliche Erhöhung der Betriebskosten und Instandhaltungskosten.",
    long: "Die Kostensteigerung berücksichtigt dass Betriebskosten, Versicherungen und Reparaturen jährlich teurer werden. Typischerweise wird hier die allgemeine Inflationsrate von 2% p.a. angesetzt. Eine höhere Kostensteigerung als Mietsteigerung reduziert den Cashflow über die Zeit." },
  { id: "dscr", term: "DSCR", category: "finanzierung",
    short: "Debt Service Coverage Ratio – zeigt ob die Mieteinnahmen die Kreditrate decken.",
    long: "Der DSCR (Debt Service Coverage Ratio) ist das Verhältnis von Mieteinnahmen zur monatlichen Kreditrate. Ein DSCR über 1 bedeutet die Miete deckt die Rate. Ein DSCR von 1,2 bedeutet die Miete ist 20% höher als die Rate. Banken fordern oft einen DSCR von mindestens 1,1–1,2 für die Kreditvergabe." },
  { id: "bruttorendite", term: "Bruttorendite", category: "rendite",
    short: "Jahresmiete geteilt durch Kaufpreis – der einfachste Renditewert.",
    long: "Die Bruttorendite berechnet sich als: (Jahresmiete / Kaufpreis) × 100. Sie ist ein erster Anhaltspunkt für die Attraktivität einer Immobilie, berücksichtigt aber weder Kosten noch Finanzierung. Für einen fairen Vergleich sollte immer auch die Nettorendite betrachtet werden." },
  { id: "nettorendite", term: "Nettorendite", category: "rendite",
    short: "Rendite nach Abzug aller Kosten – realistischer als die Bruttorendite.",
    long: "Die Nettorendite berücksichtigt alle laufenden Kosten: (Jahresmiete − Betriebskosten − Rücklage − Leerstand) / Gesamtinvestition × 100. Sie ist aussagekräftiger als die Bruttorendite und gibt an was die Immobilie nach Kosten tatsächlich abwirft." },
  { id: "cashflow", term: "Cashflow", category: "rendite",
    short: "Monatlicher Überschuss oder Fehlbetrag nach allen Einnahmen und Ausgaben.",
    long: "Der monatliche Cashflow ist: Miete − Kreditrate − Betriebskosten − Rücklage − Leerstandspuffer. Ein positiver Cashflow bedeutet die Immobilie verdient sich selbst. Ein negativer Cashflow bedeutet du musst monatlich draufzahlen (was kurzfristig bei Wertsteigerung trotzdem sinnvoll sein kann)." },
];
