/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewingRouteImport } from './routes/viewing'
import { Route as RechnerRouteImport } from './routes/rechner'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as FollowupsRouteImport } from './routes/followups'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AssumptionsRouteImport } from './routes/assumptions'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesNewRouteImport } from './routes/properties.new'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'

const ViewingRoute = ViewingRouteImport.update({
  id: '/viewing',
  path: '/viewing',
  getParentRoute: () => rootRouteImport,
} as any)
const RechnerRoute = RechnerRouteImport.update({
  id: '/rechner',
  path: '/rechner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupsRoute = FollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssumptionsRoute = AssumptionsRouteImport.update({
  id: '/assumptions',
  path: '/assumptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesNewRoute = PropertiesNewRouteImport.update({
  id: '/properties/new',
  path: '/properties/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/analyze': typeof AnalyzeRoute
  '/assumptions': typeof AssumptionsRoute
  '/dashboard': typeof DashboardRoute
  '/followups': typeof FollowupsRoute
  '/pipeline': typeof PipelineRoute
  '/projects': typeof ProjectsRoute
  '/rechner': typeof RechnerRoute
  '/viewing': typeof ViewingRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/new': typeof PropertiesNewRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/analyze': typeof AnalyzeRoute
  '/assumptions': typeof AssumptionsRoute
  '/dashboard': typeof DashboardRoute
  '/followups': typeof FollowupsRoute
  '/pipeline': typeof PipelineRoute
  '/projects': typeof ProjectsRoute
  '/rechner': typeof RechnerRoute
  '/viewing': typeof ViewingRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/new': typeof PropertiesNewRoute
  '/properties': typeof PropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/analyze': typeof AnalyzeRoute
  '/assumptions': typeof AssumptionsRoute
  '/dashboard': typeof DashboardRoute
  '/followups': typeof FollowupsRoute
  '/pipeline': typeof PipelineRoute
  '/projects': typeof ProjectsRoute
  '/rechner': typeof RechnerRoute
  '/viewing': typeof ViewingRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/new': typeof PropertiesNewRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/analyze'
    | '/assumptions'
    | '/dashboard'
    | '/followups'
    | '/pipeline'
    | '/projects'
    | '/rechner'
    | '/viewing'
    | '/properties/$id'
    | '/properties/new'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analyze'
    | '/assumptions'
    | '/dashboard'
    | '/followups'
    | '/pipeline'
    | '/projects'
    | '/rechner'
    | '/viewing'
    | '/properties/$id'
    | '/properties/new'
    | '/properties'
  id:
    | '__root__'
    | '/analyze'
    | '/assumptions'
    | '/dashboard'
    | '/followups'
    | '/pipeline'
    | '/projects'
    | '/rechner'
    | '/viewing'
    | '/properties/$id'
    | '/properties/new'
    | '/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AnalyzeRoute: typeof AnalyzeRoute
  AssumptionsRoute: typeof AssumptionsRoute
  DashboardRoute: typeof DashboardRoute
  FollowupsRoute: typeof FollowupsRoute
  PipelineRoute: typeof PipelineRoute
  ProjectsRoute: typeof ProjectsRoute
  RechnerRoute: typeof RechnerRoute
  ViewingRoute: typeof ViewingRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  PropertiesNewRoute: typeof PropertiesNewRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viewing': {
      id: '/viewing'
      path: '/viewing'
      fullPath: '/viewing'
      preLoaderRoute: typeof ViewingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechner': {
      id: '/rechner'
      path: '/rechner'
      fullPath: '/rechner'
      preLoaderRoute: typeof RechnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followups': {
      id: '/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof FollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assumptions': {
      id: '/assumptions'
      path: '/assumptions'
      fullPath: '/assumptions'
      preLoaderRoute: typeof AssumptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/new': {
      id: '/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof PropertiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AnalyzeRoute: AnalyzeRoute,
  AssumptionsRoute: AssumptionsRoute,
  DashboardRoute: DashboardRoute,
  FollowupsRoute: FollowupsRoute,
  PipelineRoute: PipelineRoute,
  ProjectsRoute: ProjectsRoute,
  RechnerRoute: RechnerRoute,
  ViewingRoute: ViewingRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  PropertiesNewRoute: PropertiesNewRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
