/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewingRouteImport } from './routes/viewing'
import { Route as VergleichRouteImport } from './routes/vergleich'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RechnerRouteImport } from './routes/rechner'
import { Route as RatgeberRouteImport } from './routes/ratgeber'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FromCalcRouteImport } from './routes/from-calc'
import { Route as FollowupsRouteImport } from './routes/followups'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AssumptionsRouteImport } from './routes/assumptions'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RechnerIndexRouteImport } from './routes/rechner.index'
import { Route as RatgeberIndexRouteImport } from './routes/ratgeber.index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as RechnerSlugRouteImport } from './routes/rechner.$slug'
import { Route as RatgeberSlugRouteImport } from './routes/ratgeber.$slug'
import { Route as PropertiesNewRouteImport } from './routes/properties.new'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as PortfolioNewRouteImport } from './routes/portfolio.new'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const ViewingRoute = ViewingRouteImport.update({
  id: '/viewing',
  path: '/viewing',
  getParentRoute: () => rootRouteImport,
} as any)
const VergleichRoute = VergleichRouteImport.update({
  id: '/vergleich',
  path: '/vergleich',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RechnerRoute = RechnerRouteImport.update({
  id: '/rechner',
  path: '/rechner',
  getParentRoute: () => rootRouteImport,
} as any)
const RatgeberRoute = RatgeberRouteImport.update({
  id: '/ratgeber',
  path: '/ratgeber',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FromCalcRoute = FromCalcRouteImport.update({
  id: '/from-calc',
  path: '/from-calc',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupsRoute = FollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AssumptionsRoute = AssumptionsRouteImport.update({
  id: '/assumptions',
  path: '/assumptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RechnerIndexRoute = RechnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RechnerRoute,
} as any)
const RatgeberIndexRoute = RatgeberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RatgeberRoute,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const RechnerSlugRoute = RechnerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RechnerRoute,
} as any)
const RatgeberSlugRoute = RatgeberSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RatgeberRoute,
} as any)
const PropertiesNewRoute = PropertiesNewRouteImport.update({
  id: '/properties/new',
  path: '/properties/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioNewRoute = PortfolioNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PortfolioRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/assumptions': typeof AssumptionsRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/followups': typeof FollowupsRoute
  '/from-calc': typeof FromCalcRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRoute
  '/ratgeber': typeof RatgeberRouteWithChildren
  '/rechner': typeof RechnerRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vergleich': typeof VergleichRoute
  '/viewing': typeof ViewingRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/portfolio/new': typeof PortfolioNewRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/new': typeof PropertiesNewRoute
  '/ratgeber/$slug': typeof RatgeberSlugRoute
  '/rechner/$slug': typeof RechnerSlugRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/ratgeber/': typeof RatgeberIndexRoute
  '/rechner/': typeof RechnerIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/assumptions': typeof AssumptionsRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/followups': typeof FollowupsRoute
  '/from-calc': typeof FromCalcRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vergleich': typeof VergleichRoute
  '/viewing': typeof ViewingRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/portfolio/new': typeof PortfolioNewRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/new': typeof PropertiesNewRoute
  '/ratgeber/$slug': typeof RatgeberSlugRoute
  '/rechner/$slug': typeof RechnerSlugRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/ratgeber': typeof RatgeberIndexRoute
  '/rechner': typeof RechnerIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/assumptions': typeof AssumptionsRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/followups': typeof FollowupsRoute
  '/from-calc': typeof FromCalcRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRoute
  '/ratgeber': typeof RatgeberRouteWithChildren
  '/rechner': typeof RechnerRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vergleich': typeof VergleichRoute
  '/viewing': typeof ViewingRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/portfolio/new': typeof PortfolioNewRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/new': typeof PropertiesNewRoute
  '/ratgeber/$slug': typeof RatgeberSlugRoute
  '/rechner/$slug': typeof RechnerSlugRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/ratgeber/': typeof RatgeberIndexRoute
  '/rechner/': typeof RechnerIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/assumptions'
    | '/auth-callback'
    | '/dashboard'
    | '/faq'
    | '/followups'
    | '/from-calc'
    | '/login'
    | '/onboarding'
    | '/pipeline'
    | '/portfolio'
    | '/pricing'
    | '/projects'
    | '/ratgeber'
    | '/rechner'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/vergleich'
    | '/viewing'
    | '/checkout/return'
    | '/portfolio/new'
    | '/properties/$id'
    | '/properties/new'
    | '/ratgeber/$slug'
    | '/rechner/$slug'
    | '/portfolio/'
    | '/properties/'
    | '/ratgeber/'
    | '/rechner/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/assumptions'
    | '/auth-callback'
    | '/dashboard'
    | '/faq'
    | '/followups'
    | '/from-calc'
    | '/login'
    | '/onboarding'
    | '/pipeline'
    | '/pricing'
    | '/projects'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/vergleich'
    | '/viewing'
    | '/checkout/return'
    | '/portfolio/new'
    | '/properties/$id'
    | '/properties/new'
    | '/ratgeber/$slug'
    | '/rechner/$slug'
    | '/portfolio'
    | '/properties'
    | '/ratgeber'
    | '/rechner'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/assumptions'
    | '/auth-callback'
    | '/dashboard'
    | '/faq'
    | '/followups'
    | '/from-calc'
    | '/login'
    | '/onboarding'
    | '/pipeline'
    | '/portfolio'
    | '/pricing'
    | '/projects'
    | '/ratgeber'
    | '/rechner'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/vergleich'
    | '/viewing'
    | '/checkout/return'
    | '/portfolio/new'
    | '/properties/$id'
    | '/properties/new'
    | '/ratgeber/$slug'
    | '/rechner/$slug'
    | '/portfolio/'
    | '/properties/'
    | '/ratgeber/'
    | '/rechner/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  AssumptionsRoute: typeof AssumptionsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  FollowupsRoute: typeof FollowupsRoute
  FromCalcRoute: typeof FromCalcRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PipelineRoute: typeof PipelineRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PricingRoute: typeof PricingRoute
  ProjectsRoute: typeof ProjectsRoute
  RatgeberRoute: typeof RatgeberRouteWithChildren
  RechnerRoute: typeof RechnerRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VergleichRoute: typeof VergleichRoute
  ViewingRoute: typeof ViewingRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  PropertiesNewRoute: typeof PropertiesNewRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viewing': {
      id: '/viewing'
      path: '/viewing'
      fullPath: '/viewing'
      preLoaderRoute: typeof ViewingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vergleich': {
      id: '/vergleich'
      path: '/vergleich'
      fullPath: '/vergleich'
      preLoaderRoute: typeof VergleichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechner': {
      id: '/rechner'
      path: '/rechner'
      fullPath: '/rechner'
      preLoaderRoute: typeof RechnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber': {
      id: '/ratgeber'
      path: '/ratgeber'
      fullPath: '/ratgeber'
      preLoaderRoute: typeof RatgeberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/from-calc': {
      id: '/from-calc'
      path: '/from-calc'
      fullPath: '/from-calc'
      preLoaderRoute: typeof FromCalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followups': {
      id: '/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof FollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assumptions': {
      id: '/assumptions'
      path: '/assumptions'
      fullPath: '/assumptions'
      preLoaderRoute: typeof AssumptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechner/': {
      id: '/rechner/'
      path: '/'
      fullPath: '/rechner/'
      preLoaderRoute: typeof RechnerIndexRouteImport
      parentRoute: typeof RechnerRoute
    }
    '/ratgeber/': {
      id: '/ratgeber/'
      path: '/'
      fullPath: '/ratgeber/'
      preLoaderRoute: typeof RatgeberIndexRouteImport
      parentRoute: typeof RatgeberRoute
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/rechner/$slug': {
      id: '/rechner/$slug'
      path: '/$slug'
      fullPath: '/rechner/$slug'
      preLoaderRoute: typeof RechnerSlugRouteImport
      parentRoute: typeof RechnerRoute
    }
    '/ratgeber/$slug': {
      id: '/ratgeber/$slug'
      path: '/$slug'
      fullPath: '/ratgeber/$slug'
      preLoaderRoute: typeof RatgeberSlugRouteImport
      parentRoute: typeof RatgeberRoute
    }
    '/properties/new': {
      id: '/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof PropertiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/new': {
      id: '/portfolio/new'
      path: '/new'
      fullPath: '/portfolio/new'
      preLoaderRoute: typeof PortfolioNewRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortfolioRouteChildren {
  PortfolioNewRoute: typeof PortfolioNewRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioNewRoute: PortfolioNewRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface RatgeberRouteChildren {
  RatgeberSlugRoute: typeof RatgeberSlugRoute
  RatgeberIndexRoute: typeof RatgeberIndexRoute
}

const RatgeberRouteChildren: RatgeberRouteChildren = {
  RatgeberSlugRoute: RatgeberSlugRoute,
  RatgeberIndexRoute: RatgeberIndexRoute,
}

const RatgeberRouteWithChildren = RatgeberRoute._addFileChildren(
  RatgeberRouteChildren,
)

interface RechnerRouteChildren {
  RechnerSlugRoute: typeof RechnerSlugRoute
  RechnerIndexRoute: typeof RechnerIndexRoute
}

const RechnerRouteChildren: RechnerRouteChildren = {
  RechnerSlugRoute: RechnerSlugRoute,
  RechnerIndexRoute: RechnerIndexRoute,
}

const RechnerRouteWithChildren =
  RechnerRoute._addFileChildren(RechnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  AssumptionsRoute: AssumptionsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  FollowupsRoute: FollowupsRoute,
  FromCalcRoute: FromCalcRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PipelineRoute: PipelineRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PricingRoute: PricingRoute,
  ProjectsRoute: ProjectsRoute,
  RatgeberRoute: RatgeberRouteWithChildren,
  RechnerRoute: RechnerRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VergleichRoute: VergleichRoute,
  ViewingRoute: ViewingRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  PropertiesNewRoute: PropertiesNewRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
